services:

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      CLUSTER_ID: ZGI1NTk0YmY3NzVjNDkSMD
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURİTY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_LOG_RETENTION_BYTES: 1073741824

    volumes:
      - kafka-data:/var/lib/kafka/data
    ports: 
      - "9092:9092"
      - "9093:9093"

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    env_file: ./order-service/.env
    depends_on:
      - kafka


volumes:
  kafka-data:
