FROM golang:1.24 AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app
RUN go build -o main .

FROM gcr.io/distroless/static:nonroot

WORKDIR /

COPY --from=builder /app/main .

EXPOSE 8001

USER nonroot:nonroot

CMD ["./main"]

